# 
policy_path: "{LEGGED_GYM_ROOT_DIR}/deploy/pre_train/adam1_servo/motion.pt"
xml_path: "{LEGGED_GYM_ROOT_DIR}/resources/robots/adam1_servo/urdf/scene.xml"

# Total simulation time
simulation_duration: 6000.0
# Simulation time step
simulation_dt: 0.002
# Controller update frequency (meets the requirement of simulation_dt * controll_decimation=0.02; 50Hz)
control_decimation: 10


kps: [5, 5, 5, 10, 3, 3, 5, 5, 5, 10, 3, 3] 
kds: [0.3, 0.3, 0.3, 0.5, 0.1, 0.1, 0.3, 0.3, 0.3, 0.5, 0.1, 0.1] 

default_angles: [0, 0, -0.15, -0.35, 0.0, -0.2, 
                 0, 0, -0.15, -0.35, 0.0, -0.2]

ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25
cmd_scale: [2.0, 2.0, 0.25]
num_actions: 12
num_obs: 47

cmd_init: [0.5, 0, 0]